#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo 'Running pre-commit hook...'

## Check for uncommitted changes
yarn check-lint || (
    echo 'TypeScript lint check failed.'
    exit 1
)

## Check tsconfing standards
yarn check-types || (
    echo 'TypeScript check failed.'
    exit 1
)

## Checking formatting
yarn check-format || (
    echo 'TypeScript formatting check failed.'
    exit 1
)

yarn build || (
    echo 'Build failed.'
    exit 1
)
