#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo 'Running pre-commit hook...'

## Check tsconfing standards
yarn check-types || (
    echo 'TypeScript check failed.'
    exit 1
)

yarn check-format || (
    echo 'TypeScript formatting check failed.'
    exit 1
)

yarn check-lint || (
    echo 'TypeScript lint check failed.'
    exit 1
)

yarn check-all ||
(
    echo 'TypeScript check failed.'
    exit 1
)