name: CI
on: [push]
jobs:
  eslint:
    name: Lint Code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install packages
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Format code 
        run: yarn format:fix

      - name: Run ESLint
        run: yarn lint
